# Data Retrieval

In [51]:
import pandas as pd
import numpy as np

import warnings
warnings.filterwarnings('ignore')

#### Original data set 'Checkouts by title':

In [52]:
spl = pd.read_csv('Data/Checkouts_by_Title.csv', thousands=',')
# thousands arg used because column Checkouts has a mix of numbers, strings, 
#and the thousand separator is denoted as ','

spl.head()

UsageClass CheckoutType MaterialType  CheckoutYear  CheckoutMonth  \
0   Physical      Horizon         BOOK          2016              6   
1    Digital    OverDrive        EBOOK          2016              6   
2   Physical      Horizon    SOUNDDISC          2016              6   
3    Digital    OverDrive        EBOOK          2016              6   
4   Physical      Horizon         BOOK          2016              6   

   Checkouts                                              Title  \
0          1  Capitalism unbound : the incontestable moral c...   
1          2  A Fountain Filled With Blood: Clare Fergusson ...   
2          3        And winter came-- [sound recording] / Enya.   
3          1                                     Simply Sensual   
4         33  Lafayette in the somewhat United States / Sara...   

                 Creator                                           Subjects  \
0      Bernstein, Andrew                                         Capitalism   
1  Julia Spencer-Fleming                                   Fiction, Mystery   
2                   Enya  Christmas music, New Age music, Popular music ...   
3         Carly Phillips             Contemporary Romance, Fiction, Romance   
4   Vowell, Sarah, 1969-  Lafayette Marie Joseph Paul Yves Roch Gilbert ...   

                      Publisher PublicationYear  
0  University Press of America,          c2010.  
1          Macmillan Publishers            2013  
2                      Reprise,          p2008.  
3   Harlequin Enterprises, Ltd.            2010  
4              Riverhead Books,           2015.

## Initial information

In [53]:
spl.shape

(33156891, 11)

In [54]:
# Data set overview

spl.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33156891 entries, 0 to 33156890
Data columns (total 11 columns):
UsageClass         object
CheckoutType       object
MaterialType       object
CheckoutYear       int64
CheckoutMonth      int64
Checkouts          int64
Title              object
Creator            object
Subjects           object
Publisher          object
PublicationYear    object
dtypes: int64(3), object(8)
memory usage: 2.7+ GB


----------
# Data Cleaning

### NaN 

In [55]:
spl.isna().sum()

UsageClass                0
CheckoutType              0
MaterialType              0
CheckoutYear              0
CheckoutMonth             0
Checkouts                 0
Title                     0
Creator            11922438
Subjects            1721680
Publisher           9495800
PublicationYear     9816305
dtype: int64

The vast ammount of NaN values we see here may be due to the combination of records made in 2016, for now I'll make them their own category and evaluate each column later on.

*"There are a few different reasons why you will sometimes find a blank subject headings field. Historic physical checkouts were combined with current Horizon bibliographic record details in December 2016. If there was not a Horizon bibliographic record for a title as of December 2016, a subject heading was not recorded.
Also, some digital items have no Horizon bibliographic record. For example, music from Freegal is not cataloged within Horizon. Thus there will be no subject headings available for those checkouts."*

In [56]:
# Creator column

spl.Creator.replace(np.nan, 'Unknown', inplace=True)

In [57]:
# Subjects column

spl.Subjects.replace(np.nan, 'Unknown', inplace=True)

In [58]:
# Publisher column

spl.Publisher.replace(np.nan, 'Unknown', inplace=True)

In [59]:
# PublicationYear column

spl.PublicationYear.replace(np.nan, 'Unknown', inplace=True)

In [60]:
# Confirm 

spl.isna().sum()

UsageClass         0
CheckoutType       0
MaterialType       0
CheckoutYear       0
CheckoutMonth      0
Checkouts          0
Title              0
Creator            0
Subjects           0
Publisher          0
PublicationYear    0
dtype: int64

### Familiarize with each column

##### UsageClass

In [61]:
# UsageClass 	Denotes if item is “physical” or “digital”

spl['UsageClass'].unique()

array(['Physical', 'Digital'], dtype=object)

##### CheckoutType

In [62]:
# CheckoutType 	Denotes the vendor tool used to check out the item

spl['CheckoutType'].unique()

array(['Horizon', 'OverDrive', 'Freegal', 'Hoopla', 'Zinio'], dtype=object)

* Freegal: stream and download songs
* OverDrive: access e-books and audiobooks
* Horizon: information portal used by the library previously
* Hoopla: stream movies or TV shows
* Zinio: digital magazines

In [63]:
spl['CheckoutType'].value_counts()

Horizon      26662540
OverDrive     5224321
Freegal        969118
Hoopla         291737
Zinio            9175
Name: CheckoutType, dtype: int64

##### MaterialType

In [64]:
# MaterialType 	Describes the type of item checked out (examples: book, song movie, music, magazine)

spl['MaterialType'].value_counts()

BOOK                           18783118
SOUNDDISC                       3871930
EBOOK                           3641919
VIDEODISC                       2886206
AUDIOBOOK                       1516061
SONG                             969118
VIDEOCASS                        499677
MUSIC                            263355
SOUNDCASS                        199701
MIXED                            132221
MOVIE                             92192
TELEVISION                        57730
CR                                49406
VIDEO                             44277
SOUNDDISC, VIDEODISC              29008
COMIC                             21492
SOUNDREC                          21401
VISUAL                            18591
KIT                               11926
ER                                10151
MAGAZINE                           9175
REGPRINT                           7387
ER, VIDEODISC                      6110
ER, SOUNDDISC                      4843
ATLAS                              3471


In [65]:
spl['MaterialType'].unique()

array(['BOOK', 'EBOOK', 'SOUNDDISC', 'ER', 'VIDEODISC', 'SONG',
       'AUDIOBOOK', 'MOVIE', 'MUSIC', 'SOUNDDISC, VIDEODISC',
       'TELEVISION', 'VIDEO', 'SOUNDREC', 'MIXED', 'MAP', 'ER, SOUNDDISC',
       'REGPRINT', 'SOUNDCASS', 'ATLAS', 'CR', 'VISUAL', 'ER, VIDEODISC',
       'MAGAZINE', 'VIDEOREC', 'LARGEPRINT', 'REGPRINT, SOUNDDISC',
       'VIDEOCASS, VIDEODISC', 'NOTATEDMUSIC', 'VIDEOCASS', 'MUSICSNDREC',
       'ER, VIDEOREC', 'SOUNDDISC, SOUNDREC', 'FLASHCARD, SOUNDDISC',
       'ER, REGPRINT', 'GLOBE', 'ER, PRINT', 'VIDEOCART',
       'SOUNDCASS, SOUNDDISC, VIDEOCASS, VIDEODISC', 'ER, NONPROJGRAPH',
       'REGPRINT, VIDEOREC', 'KIT', 'SLIDE, VIDEOCASS', 'SLIDE',
       'MICROFORM', 'COMIC', 'PICTURE', 'SOUNDCASS, SOUNDDISC',
       'SLIDE, SOUNDCASS, VIDEOCASS', 'FLASHCARD', 'CHART',
       'SOUNDDISC, VIDEOCASS', 'UNSPECIFIED', 'REMOTESEN', 'PRINT',
       'COMPFILE', 'NONPROJGRAPH', 'SLIDE, SOUNDCASS',
       'SOUNDCASS, VIDEOCASS', 'ATLAS, ER', 'ER, MAP',
       'PICTUR

#### Here I will move the types with double categories to a single general classification of similar type. The type ER corresponds to formats that are print + media; so they are grouped into one single category.

In [66]:
# ER is Book/Print + Media
 
spl.loc[spl['MaterialType'] == 'ER, SOUNDDISC', 'MaterialType'] = 'ER'
spl.loc[spl['MaterialType'] == 'ER, VIDEODISC', 'MaterialType'] = 'ER'
spl.loc[spl['MaterialType'] == 'ER, VIDEOREC', 'MaterialType'] = 'ER'
spl.loc[spl['MaterialType'] == 'ER, REGPRINT', 'MaterialType'] = 'ER'
spl.loc[spl['MaterialType'] == 'ER, PRINT', 'MaterialType'] = 'ER'
spl.loc[spl['MaterialType'] == 'ER, NONPROJGRAPH', 'MaterialType'] = 'ER'
spl.loc[spl['MaterialType'] == 'ATLAS, ER', 'MaterialType'] = 'ER'
spl.loc[spl['MaterialType'] == 'ER, MAP', 'MaterialType'] = 'ER'
spl.loc[spl['MaterialType'] == 'ER, SOUNDDISC, VIDEODISC', 'MaterialType'] = 'ER'
spl.loc[spl['MaterialType'] == 'ER, VIDEOCASS', 'MaterialType'] = 'ER'
spl.loc[spl['MaterialType'] == 'ER, PICTURE', 'MaterialType'] = 'ER'

In [67]:
spl.loc[spl['MaterialType'] == 'SOUNDDISC, VIDEODISC', 'MaterialType'] = 'SOUNDCASS, SOUNDDISC, VIDEOCASS, VIDEODISC'
spl.loc[spl['MaterialType'] == 'VIDEOCASS, VIDEODISC', 'MaterialType'] = 'SOUNDCASS, SOUNDDISC, VIDEOCASS, VIDEODISC'
spl.loc[spl['MaterialType'] == 'SOUNDCASS, SOUNDDISC', 'MaterialType'] = 'SOUNDCASS, SOUNDDISC, VIDEOCASS, VIDEODISC'
spl.loc[spl['MaterialType'] == 'SOUNDDISC, VIDEOCASS', 'MaterialType'] = 'SOUNDCASS, SOUNDDISC, VIDEOCASS, VIDEODISC'
spl.loc[spl['MaterialType'] == 'SOUNDCASS, VIDEOCASS', 'MaterialType'] = 'SOUNDCASS, SOUNDDISC, VIDEOCASS, VIDEODISC'

In [68]:
spl.loc[spl['MaterialType'] == 'REGPRINT, SOUNDDISC', 'MaterialType'] = 'REGPRINT'
spl.loc[spl['MaterialType'] == 'REGPRINT, VIDEOREC', 'MaterialType'] = 'REGPRINT'

In [69]:
spl.loc[spl['MaterialType'] == 'SLIDE, VIDEOCASS', 'MaterialType'] = 'SLIDE'
spl.loc[spl['MaterialType'] == 'SLIDE, SOUNDCASS, VIDEOCASS', 'MaterialType'] = 'SLIDE'
spl.loc[spl['MaterialType'] == 'SLIDE, SOUNDCASS', 'MaterialType'] = 'SLIDE'

In [70]:
spl.loc[spl['MaterialType'] == 'FLASHCARD, SOUNDDISC', 'MaterialType'] = 'FLASHCARD'

In [71]:
spl.loc[spl['MaterialType'] == 'SOUNDDISC, SOUNDREC', 'MaterialType'] = 'SOUNDREC'

In [72]:
spl.loc[spl['MaterialType'] == 'PICTURE, VIDEODISC', 'MaterialType'] = 'PICTURE'

In [73]:
spl.loc[spl['MaterialType'] == 'MAP, VIEW', 'MaterialType'] = 'MAP'

In [74]:
# new counts

spl['MaterialType'].value_counts()

BOOK                                          18783118
SOUNDDISC                                      3871930
EBOOK                                          3641919
VIDEODISC                                      2886206
AUDIOBOOK                                      1516061
SONG                                            969118
VIDEOCASS                                       499677
MUSIC                                           263355
SOUNDCASS                                       199701
MIXED                                           132221
MOVIE                                            92192
TELEVISION                                       57730
CR                                               49406
VIDEO                                            44277
SOUNDCASS, SOUNDDISC, VIDEOCASS, VIDEODISC       29515
SOUNDREC                                         21549
COMIC                                            21492
ER                                               21423
VISUAL    

##### CheckoutYear

In [75]:
spl['CheckoutYear'].unique()

array([2016, 2017, 2018, 2019, 2005, 2006, 2007, 2008, 2009, 2010, 2011,
       2012, 2013, 2014, 2015])

##### CheckoutMonth

In [77]:
# CheckoutMonth 	The month of checkout for this record

spl['CheckoutMonth'].unique()

array([ 6,  7,  8,  9, 10,  3,  2,  1,  4,  5, 11, 12])

##### Ckeckouts

In [79]:
spl.Checkouts.unique()

array([   1,    2,    3,   33,    4,    5,   47,    7,    9,    6,   21,
         18,   24,    8,   14,   13,   10,   72,   15,   17,   11,  146,
         35,   12,   29,   49,   37,   90,   23,  115,   16,   20,   28,
         26,   78,   22,   65,   96,   19,   40,   44,   48,  103,   30,
         56,   53,   31,   95,   32,   34,  114,   86,   39,   51,   27,
        135,   41,   36,   38,   80,   45,   42,   25,   62,   58,  117,
        241,   50,   43,   61,  166,  191,  198,   60,   59,  124,   75,
        232,  105,   52,   55,   68,   87,   46,   93,  219,   94,  120,
        340,  140,  123,   71,   63,   69,   91,  130,  131,   66,  206,
        145,   76,  132,  144,  192,   57,   54,  142,   67,  128,  112,
         82,  155,  165,  102,   99,  401,   73,  101,   79,  176,  207,
        237,   81,   64,   83,  224,   84,  111,  157,   89,  177,  138,
         74,  170,  108,  298,  127,  129,  259,   85,   70,  188,   88,
        137,  121,  160,  292,   97,  109,  616,  1

##### PublicationYear

In [80]:
# PublicationYear	The year from the catalog record in which the item was published, printed, or copyrighted. 

spl['PublicationYear'].unique()

array(['c2010.', '2013', 'p2008.', ..., '©1943.', '1969 [c1965]',
       'Spencer-Walker Press, 1988.'], dtype=object)

### At this point I save a clean version of the data for future use.

In [81]:
# Confirm all data types

spl.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33156891 entries, 0 to 33156890
Data columns (total 11 columns):
UsageClass         object
CheckoutType       object
MaterialType       object
CheckoutYear       int64
CheckoutMonth      int64
Checkouts          int64
Title              object
Creator            object
Subjects           object
Publisher          object
PublicationYear    object
dtypes: int64(3), object(8)
memory usage: 2.7+ GB


In [82]:
spl.to_csv('Data/spl_clean.csv', index=False)

## Sources
* https://stackoverflow.com/questions/22137723/convert-number-strings-with-commas-in-pandas-dataframe-to-float