# Properties of Dot Product - Lab

## Introduction

In this lab we shall look at some interesting properties of a Dot product type matrix multiplication. Understanding these properties will become useful as we move forward with machine learning advanced linear algebra. The lab will require you to calculate results to provide a proof for these properties.

## Objectives
You will be able to:
* Understand and analytically explain Distributive, Commutative and Associative properties of dot product

## Instructions

* For each property, create suitably sized matrices with random data and prove the equations 
* Ensure that size/dimension assumptions are met while performing calculations (you'll see errors otherwise)
* Calculate the LHS and RHS for all equations and show if they are equal or not

In [2]:
import numpy as np
import random

## Distributive Property - Matrices multiplication is distributive
### Prove that A.(B+C)=A.B+A.C

In [20]:
A = np.random.randint(5, size=4)
B = np.random.randint(10, size=(4,4))
C = np.random.randint(10, size=(4,4))

print(A)
print(B)
print(C)

[3 0 1 2]
[[2 0 7 2]
 [6 8 9 0]
 [7 8 6 9]
 [6 2 3 9]]
[[4 6 1 9]
 [4 9 7 9]
 [1 0 5 9]
 [5 9 9 0]]


In [21]:
#LHS
left = A.dot(B+C)
print(left)

#RHS
right = A.dot(B) + A.dot(C)
print(right)

print(left == right)

[48 48 59 69]
[48 48 59 69]
[ True  True  True  True]


## Associative Property - Matrices multiplication is associative
### Prove that A.(B.C)=(A.B).C

In [28]:
A = np.random.randint(10, size=(4,3))
B = np.random.randint(10, size=(3,2))
C = np.random.randint(10, size=(2,3))

print(A)
print(B)
print(C)

[[4 6 6]
 [5 1 3]
 [7 9 7]
 [0 3 1]]
[[9 0]
 [3 2]
 [7 8]]
[[7 7 7]
 [5 7 7]]


In [29]:
#LHS
left = A.dot(B.dot(C))
print(left)

#RHS
right = (A.dot(B)).dot(C)
print(right)

print(left == right)

[[ 972 1092 1092]
 [ 613  665  665]
 [1343 1491 1491]
 [ 182  210  210]]
[[ 972 1092 1092]
 [ 613  665  665]
 [1343 1491 1491]
 [ 182  210  210]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]]


## Commutative Property - Matrix multiplication is NOT commutative
### Prove that for matrices, A.B ≠ B.A

In [32]:
A = np.random.randint(10, size=(4,3))
B = np.random.randint(10, size=(3,4))

print(A)
print(B)

[[4 3 7]
 [9 9 4]
 [7 5 9]
 [6 7 5]]
[[0 1 9 3]
 [1 7 8 6]
 [1 7 5 2]]


In [33]:
left = A.dot(B)
righ = B.dot(A)

print(left)
print(right)
print(left == right)

[[ 10  74  95  44]
 [ 13 100 173  89]
 [ 14 105 148  69]
 [ 12  90 135  70]]
[[ 972 1092 1092]
 [ 613  665  665]
 [1343 1491 1491]
 [ 182  210  210]]
False


/Users/natalia/anaconda3/envs/learn-env/lib/python3.6/site-packages/ipykernel_launcher.py:6: DeprecationWarning: elementwise == comparison failed; this will raise an error in the future.
  


## Commutative Property -  vector multiplication IS commutative
### Prove that for vectors, x<sup>T</sup> . y = y<sup>T</sup> . x
Note: superscipt<sup>T</sup> denotes the transpose we saw earlier

In [42]:
x = np.random.randint(10, size=5)
y = np.random.randint(10, size=5)

print(x)
print(y)

[5 2 9 7 4]
[2 8 3 1 4]


In [44]:
left = (np.transpose(x)).dot(y)
print(left)

right = (np.transpose(y).dot(x))
print(right)

76
76


#### and finally 
## Simplification of the matrix product
### Prove that  (A.B)<sup>T</sup> = B<sup>T</sup> . A<sup>T</sup>

In [45]:
A = np.random.randint(10, size=(4,4))
B = np.random.randint(10, size=(4,4))

print(A)
print(B)

[[5 3 2 7]
 [1 0 4 0]
 [9 5 3 8]
 [4 0 8 7]]
[[9 4 2 5]
 [4 8 1 6]
 [4 9 3 5]
 [1 2 2 6]]


In [46]:
left = np.transpose(A.dot(B))
print(left)
right = (np.transpose(B)).dot(np.transpose(A))
print(right)
print(left == right)

[[ 72  25 121  75]
 [ 76  40 119 102]
 [ 33  14  48  46]
 [ 95  25 138 102]]
[[ 72  25 121  75]
 [ 76  40 119 102]
 [ 33  14  48  46]
 [ 95  25 138 102]]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


## Summary 

So now we have seen enough matrix algebra to help us solve a problem of linear equations as we saw earlier in this section. We shall see how to do this next. 